# Source: cluster-autoscaler/templates/rbac-for-mgmt-cluster-access.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-autoscaler-management
  namespace: 8ba57270-08d7-493d-89c5-2be93a1e9745
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-autoscaler-management
subjects:
- kind: ServiceAccount
  name: cluster-autoscaler
  namespace: 8ba57270-08d7-493d-89c5-2be93a1e9745

