---
# Source: cluster-autoscaler/templates/rbac-for-mgmt-cluster-access.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler
  namespace: 8ba57270-08d7-493d-89c5-2be93a1e9745
