# Source: cluster-api-aws/templates/job-check.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: 8ba57270-08d7-493d-89c5-2be93a1e9745-capi-aws-check
  namespace: 8ba57270-08d7-493d-89c5-2be93a1e9745
spec:
  template:
    metadata:
      name: 8ba57270-08d7-493d-89c5-2be93a1e9745-capi-aws
    spec:
      serviceAccountName: 8ba57270-08d7-493d-89c5-2be93a1e9745-capi-aws
      containers:
      - name: wait-for-ready
        image: "ghcr.io/openinfradev/python_kubectl_argo:v1.1.0"
        imagePullPolicy: IfNotPresent
        command:
        - timeout 
        - 5m
        - /wait_for_kubeconfig.sh  
        - 8ba57270-08d7-493d-89c5-2be93a1e9745
        - 8ba57270-08d7-493d-89c5-2be93a1e9745
        volumeMounts:
        - name: vol
          subPath: wait_for_kubeconfig.sh
          mountPath: /wait_for_kubeconfig.sh
      volumes:
      - name: vol
        configMap:
          name: 8ba57270-08d7-493d-89c5-2be93a1e9745-capi-aws
          defaultMode: 0555
      restartPolicy: OnFailure
